### ISSUE TITLE
Feature Extraction repo

### ISSUE THREAD

**Issue by HeydarSoudani** [Vastlab/SSFiOWL#6]
Feature Extraction repo "https://github.com/Vastlab/vast/blob/main/tools/FeatureExtraction.py" does not exist

**Comment by akshay-raj-dhamija** [comment]
Thanks for bringing this to our attention.
The file was renamed and moved, you may use either `FromCSV.py` or `FromDirectoryStructures.py` present at https://github.com/Vastlab/vast/tree/main/tools/FeatureExtractors for feature extraction depending on if you want to extract features only for certain images listed in a CSV or all images existing in a directory.
Please note we plan to move this feature extraction script to another location in the future, but you should be able to locate it in https://github.com/Vastlab/vast, will update the README here once this is done.

**Comment by akshay-raj-dhamija** [comment]
The feature extraction scripts are now located at https://github.com/Vastlab/vast/tree/main/vast/scripts/FeatureExtractors and the README has been updated accordingly.
